@startuml
class User{
        username : String
        password : String
        email : String
        name : String
        lastname : String
        DNI : String
}
class Comitee{
}

class Secretary {
}

class President {
}


class JobApplication {
}

class Phase {
}
class Applicants {
}
class Qualifications {
}
class Document {
}

User "5" --> "*" Comitee:Belongs >

Qualifications "*" -- "1" Comitee:Evaluate <

Comitee "1" -- "1" JobApplication:Administrates >
Comitee <|-- (Secretary, President)

Document "*" --> "*" Phase:Have <
JobApplication "1" o-- "3" Phase:Have > 

JobApplication "1" o-- "*" Applicants:Have >
Qualifications "5" -- "1" Applicants:Evaluated by < 
Document "*" --> "0..1" Applicants:Belongs >
@enduml
