@startuml
class User{
        username : String
        password : String
        email : String
        name : String
        lastname : String
        DNI : String
}
class Comitee{
  rank: Enumerable
}



class JobApplication {
name: String
description: String
requirements: List<String>
evaluationCriteria: List<String>
currentPhase: Phase
}

class Phase {
phaseNumber: int
name: String
initialDate: DateTime
finalDate: DateTime
}
class Applicants {
        email : String
        name : String
        lastname : String
        DNI : String
}
class Qualifications {
mark: int
observation: String
}
class Document {
name: String
path: String
}

User "1" --> "*" Comitee:Belongs >

Qualifications "*" -- "1" Comitee:Evaluate <

Comitee "5" -- "1" JobApplication:Administrates >

Document "*" --> "*" Phase:Have <
JobApplication "1" o-- "3" Phase:Have > 

JobApplication "1" o-- "*" Applicants:Have >
Qualifications "5" -- "1" Applicants:Evaluated by < 
Document "*" --> "0..1" Applicants:Belongs >
@enduml
