# This workflow will build a Java project with Maven and then deploys it to Heroku using Docker
# For more information see:
#  - https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#  - https://github.com/marketplace/actions/deploy-docker-image-to-heroku-app

name: CI with Maven and CD with Heroku and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build, Push and Deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        uses: jctaveras/heroku-deploy@v2.1.1  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: 'academicrecruitapi-gei'
          dockerfile_path: ''
